apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: {{ .Values.allowEmptyPassword | default "no" | quote }}
        - name: MARIADB_HOST
          value: {{ .Values.externalDatabase.host | quote }}
        - name: MARIADB_PORT_NUMBER
          value: {{ .Values.externalDatabase.port | default "3306" | quote }}
        - name: WORDPRESS_DATABASE_NAME
          value: {{ .Values.externalDatabase.database | quote }}
        - name: WORDPRESS_DATABASE_USER
          value: {{ .Values.externalDatabase.user | quote }}
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "externaldb" }}
              key: db-password
        - name: WORDPRESS_USERNAME
          value: {{ default "" .Values.wordpressUsername | quote }}
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: wordpress-password
        - name: WORDPRESS_EMAIL
          value: {{ default "" .Values.wordpressEmail | quote }}
        - name: WORDPRESS_FIRST_NAME
          value: {{ default "" .Values.wordpressFirstName | quote }}
        - name: WORDPRESS_LAST_NAME
          value: {{ default "" .Values.wordpressLastName | quote }}
        - name: WORDPRESS_BLOG_NAME
          value: {{ default "" .Values.wordpressBlogName | quote }}
        - name: SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: smtp-password
        - name: SMTP_USERNAME
          value: {{ default "" .Values.smtpUsername | quote }}
        - name: SMTP_PROTOCOL
          value: {{ default "" .Values.smtpProtocol | quote }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
#         livenessProbe:
#           httpGet:
#             path: /wp-login.php
#           {{- if not .Values.healthcheckHttps }}
#             port: http
#           {{- else }}
#             port: https
#             scheme: HTTPS
#           {{- end }}
# {{ toYaml .Values.livenessProbe | indent 10 }}
#         readinessProbe:
#           httpGet:
#             path: /wp-login.php
#           {{- if not .Values.healthcheckHttps }}
#             port: http
#           {{- else }}
#             port: https
#             scheme: HTTPS
#           {{- end }}
{{ toYaml .Values.readinessProbe | indent 10 }}
        volumeMounts:
        - mountPath: /bitnami/apache
          name: wordpress-data
          subPath: apache
        - mountPath: /bitnami/wordpress
          name: wordpress-data
          subPath: wordpress
        - mountPath: /bitnami/php
          name: wordpress-data
          subPath: php
        resources:
{{ toYaml .Values.resources | indent 10 }}
      - name: cloudcmd
        image: coderaiser/cloudcmd
        ports:
        - name: cloudcmd
          containerPort: 8000
        env:
        - name: CLOUDCMD_ROOT
          value: /mnt/fs
        - name: CLOUDCMD_AUTH
          value: "true"
        - name: CLOUDCMD_USERNAME
          value: {{ .Values.cloudcmdUsername }}
        - name: CLOUDCMD_PASSWORD
          value: {{ .Values.cloudcmdPassword }}
        volumeMounts:
        - mountPath: /mnt/fs
          name: wordpress-data
          subPath: wordpress
      volumes:
      - name: wordpress-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- else }}
        emptyDir: {}
      {{ end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end -}}
